# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Regexp-Log-BlueCoat
version:      0.03
version_from: lib/Regexp/Log/BlueCoat.pm
installdirs:  site
requires:
    Regexp::Log:                   0.01
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
